<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dataport.Terminfinder.Common\Dataport.Terminfinder.Common.csproj" />
    <ProjectReference Include="..\Dataport.Terminfinder.Repository\Dataport.Terminfinder.Repository.csproj" />
  </ItemGroup>

</Project>
